<template>
  <div class="vote-page-container">
    <b-field label="Nickname">
      <b-input v-model="nickname"></b-input>
    </b-field>

    <b-field label="Search music">
      <b-autocomplete
        v-model="search"
        placeholder="e.g. New Rules"
        :keep-first="true"
        :open-on-focus="true"
        :data="filteredMusic"
        :disabled="isMusicComplete"
        field="name"
        @select="selectMusic($event)"
      >
      </b-autocomplete>
    </b-field>
    <music-list
      :musics="selectedMusic"
      @delete="deleteMusic($event)"
    />
    <div class="buttons">
      <b-button
        type="is-primary"
        expanded
        :disabled="!isFormComplete"
      >Vote</b-button>
    </div>
  </div>
</template>

<script>
import MusicList from '../components/organisms/MusicList.vue';

export default {
  name: 'VotePage',
  components: {
    MusicList,
  },
  data() {
    return {
      search: '',
      nickname: '',
      selectedMusic: [],
      musics: [
        {
          id: '6DCZcSspjsKoFjzjrWoCd',
          name: "God's Plan",
          artists: 'Drake',
          genre: 'Hip-Hop/Rap',
          danceability: 0.754,
          energy: 0.449,
          key: 7,
          loudness: -9.211,
          mode: 1,
          speechiness: 0.109,
          acousticness: 0.0332,
          instrumentalness: 0.0000829,
          liveness: 0.552,
          valence: 0.357,
          tempo: 77.169,
          duration_ms: 198973,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '3ee8Jmje8o58CHK66QrVC',
          name: 'SAD!',
          artists: 'XXXTENTACION',
          genre: 'Hip-Hop/Rap',
          danceability: 0.74,
          energy: 0.613,
          key: 8,
          loudness: -4.88,
          mode: 1,
          speechiness: 0.145,
          acousticness: 0.258,
          instrumentalness: 0.00372,
          liveness: 0.123,
          valence: 0.473,
          tempo: 75.023,
          duration_ms: 166606,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '0e7ipj03S05BNilyu5bRz',
          name: 'rockstar (feat. 21 Savage)',
          artists: 'Post Malone',
          genre: 'Hip-Hop/Rap',
          danceability: 0.587,
          energy: 0.535,
          key: 5,
          loudness: -6.09,
          mode: 0,
          speechiness: 0.0898,
          acousticness: 0.117,
          instrumentalness: 0.0000656,
          liveness: 0.131,
          valence: 0.14,
          tempo: 159.847,
          duration_ms: 218147,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '3swc6WTsr7rl9DqQKQA55',
          name: 'Psycho (feat. Ty Dolla $ign)',
          artists: 'Post Malone',
          genre: 'Hip-Hop/Rap',
          danceability: 0.739,
          energy: 0.559,
          key: 8,
          loudness: -8.011,
          mode: 1,
          speechiness: 0.117,
          acousticness: 0.58,
          instrumentalness: 0,
          liveness: 0.112,
          valence: 0.439,
          tempo: 140.124,
          duration_ms: 221440,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '2G7V7zsVDxg1yRsu7Ew9R',
          name: 'In My Feelings',
          artists: 'Drake',
          genre: 'Hip-Hop/Rap',
          danceability: 0.835,
          energy: 0.626,
          key: 1,
          loudness: -5.833,
          mode: 1,
          speechiness: 0.125,
          acousticness: 0.0589,
          instrumentalness: 0.00006,
          liveness: 0.396,
          valence: 0.35,
          tempo: 91.03,
          duration_ms: 217925,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '7dt6x5M1jzdTEt8oCbisT',
          name: 'Better Now',
          artists: 'Post Malone',
          genre: 'Hip-Hop/Rap',
          danceability: 0.68,
          energy: 0.563,
          key: 10,
          loudness: -5.843,
          mode: 1,
          speechiness: 0.0454,
          acousticness: 0.354,
          instrumentalness: 0,
          liveness: 0.136,
          valence: 0.374,
          tempo: 145.028,
          duration_ms: 231267,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '58q2HKrzhC3ozto2nDdN4',
          name: 'I Like It',
          artists: 'Cardi B',
          genre: 'Hip-Hop/Rap',
          danceability: 0.816,
          energy: 0.726,
          key: 5,
          loudness: -3.998,
          mode: 0,
          speechiness: 0.129,
          acousticness: 0.099,
          instrumentalness: 0,
          liveness: 0.372,
          valence: 0.65,
          tempo: 136.048,
          duration_ms: 253390,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '7ef4DlsgrMEH11cDZd32M',
          name: 'One Kiss (with Dua Lipa)',
          artists: 'Calvin Harris',
          genre: 'Dance/Electronic',
          danceability: 0.791,
          energy: 0.862,
          key: 9,
          loudness: -3.24,
          mode: 0,
          speechiness: 0.11,
          acousticness: 0.037,
          instrumentalness: 0.0000219,
          liveness: 0.0814,
          valence: 0.592,
          tempo: 123.994,
          duration_ms: 214847,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '76cy1WJvNGJTj78UqeA5z',
          name: 'IDGAF',
          artists: 'Dua Lipa',
          genre: 'Pop',
          danceability: 0.836,
          energy: 0.544,
          key: 7,
          loudness: -5.975,
          mode: 1,
          speechiness: 0.0943,
          acousticness: 0.0403,
          instrumentalness: 0,
          liveness: 0.0824,
          valence: 0.51,
          tempo: 97.028,
          duration_ms: 217947,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '08bNPGLD8AhKpnnERrAc6',
          name: 'FRIENDS',
          artists: 'Marshmello',
          genre: 'Dance/Electronic',
          danceability: 0.626,
          energy: 0.88,
          key: 9,
          loudness: -2.384,
          mode: 0,
          speechiness: 0.0504,
          acousticness: 0.205,
          instrumentalness: 0,
          liveness: 0.128,
          valence: 0.534,
          tempo: 95.079,
          duration_ms: 202621,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '1rfofaqEpACxVEHIZBJe6',
          name: 'Havana',
          artists: 'Camila Cabello',
          genre: 'Pop',
          danceability: 0.765,
          energy: 0.523,
          key: 2,
          loudness: -4.333,
          mode: 1,
          speechiness: 0.03,
          acousticness: 0.184,
          instrumentalness: 0.0000356,
          liveness: 0.132,
          valence: 0.394,
          tempo: 104.988,
          duration_ms: 217307,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '0s3nnoMeVWz3989MkNQiR',
          name: 'Lucid Dreams',
          artists: 'Juice WRLD',
          genre: 'Hip-Hop/Rap',
          danceability: 0.511,
          energy: 0.566,
          key: 6,
          loudness: -7.23,
          mode: 0,
          speechiness: 0.2,
          acousticness: 0.349,
          instrumentalness: 0,
          liveness: 0.34,
          valence: 0.218,
          tempo: 83.903,
          duration_ms: 239836,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '3CA9pLiwRIGtUBiMjbZmR',
          name: 'Nice For What',
          artists: 'Drake',
          genre: 'Hip-Hop/Rap',
          danceability: 0.586,
          energy: 0.909,
          key: 8,
          loudness: -6.474,
          mode: 1,
          speechiness: 0.0705,
          acousticness: 0.0891,
          instrumentalness: 0.000109,
          liveness: 0.119,
          valence: 0.757,
          tempo: 93.394,
          duration_ms: 210747,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '7fa9MBXhVfQ8P8Df9OEbD',
          name: 'Girls Like You (feat. Cardi B)',
          artists: 'Maroon 5',
          genre: 'Pop',
          danceability: 0.851,
          energy: 0.541,
          key: 0,
          loudness: -6.825,
          mode: 1,
          speechiness: 0.0505,
          acousticness: 0.568,
          instrumentalness: 0,
          liveness: 0.13,
          valence: 0.448,
          tempo: 124.959,
          duration_ms: 235545,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '09IStsImFySgyp0pIQdqA',
          name: 'The Middle',
          artists: 'Zedd',
          genre: 'Pop',
          danceability: 0.753,
          energy: 0.657,
          key: 7,
          loudness: -3.061,
          mode: 1,
          speechiness: 0.0449,
          acousticness: 0.171,
          instrumentalness: 0,
          liveness: 0.112,
          valence: 0.437,
          tempo: 107.01,
          duration_ms: 184732,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '3GCdLUSnKSMJhs4Tj6CV3',
          name: 'All The Stars (with SZA)',
          artists: 'Kendrick Lamar',
          genre: 'Hip-Hop/Rap',
          danceability: 0.698,
          energy: 0.633,
          key: 8,
          loudness: -4.946,
          mode: 1,
          speechiness: 0.0597,
          acousticness: 0.0605,
          instrumentalness: 0.000194,
          liveness: 0.0926,
          valence: 0.552,
          tempo: 96.924,
          duration_ms: 232187,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '2qT1uLXPVPzGgFOx4jtEu',
          name: 'no tears left to cry',
          artists: 'Ariana Grande',
          genre: 'Pop',
          danceability: 0.699,
          energy: 0.713,
          key: 9,
          loudness: -5.507,
          mode: 0,
          speechiness: 0.0594,
          acousticness: 0.04,
          instrumentalness: 0.00000311,
          liveness: 0.294,
          valence: 0.354,
          tempo: 121.993,
          duration_ms: 205920,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '39N9RPD9MRb5WmoLzNzPe',
          name: 'X',
          artists: 'Nicky Jam',
          genre: 'Reggaeton',
          danceability: 0.595,
          energy: 0.773,
          key: 9,
          loudness: -4.736,
          mode: 0,
          speechiness: 0.0549,
          acousticness: 0.0364,
          instrumentalness: 0.00108,
          liveness: 0.334,
          valence: 0.711,
          tempo: 180.073,
          duration_ms: 173628,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '0JP9xo3adEtGSdUEISisz',
          name: 'Moonlight',
          artists: 'XXXTENTACION',
          genre: 'Hip-Hop/Rap',
          danceability: 0.921,
          energy: 0.537,
          key: 9,
          loudness: -5.723,
          mode: 0,
          speechiness: 0.0804,
          acousticness: 0.556,
          instrumentalness: 0.00404,
          liveness: 0.102,
          valence: 0.711,
          tempo: 128.009,
          duration_ms: 135090,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '4qKcDkK6siZ7Jp1Jb4m0a',
          name: 'Look Alive (feat. Drake)',
          artists: 'BlocBoy JB',
          genre: 'Hip-Hop/Rap',
          danceability: 0.922,
          energy: 0.581,
          key: 10,
          loudness: -7.495,
          mode: 1,
          speechiness: 0.27,
          acousticness: 0.00104,
          instrumentalness: 0.0000586,
          liveness: 0.105,
          valence: 0.595,
          tempo: 140.022,
          duration_ms: 181263,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '5CLGzJsGqhCEECcpnFQA8',
          name: 'These Days (feat. Jess Glynne, Macklemore & Dan Caplen)',
          artists: 'Rudimental',
          genre: 'Dance/Electronic',
          danceability: 0.653,
          energy: 0.809,
          key: 0,
          loudness: -4.057,
          mode: 1,
          speechiness: 0.0474,
          acousticness: 0.194,
          instrumentalness: 0,
          liveness: 0.165,
          valence: 0.55,
          tempo: 92.213,
          duration_ms: 210773,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '3V8UKqhEK5zBkBb6d6ub8',
          name: 'Te Bot? - Remix',
          artists: 'Nio Garcia',
          genre: 'Reggaeton',
          danceability: 0.903,
          energy: 0.675,
          key: 11,
          loudness: -3.445,
          mode: 0,
          speechiness: 0.214,
          acousticness: 0.542,
          instrumentalness: 0.0000128,
          liveness: 0.0595,
          valence: 0.442,
          tempo: 96.507,
          duration_ms: 417920,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '7uzmGiiJyRfuViKKK3lVm',
          name: 'Mine',
          artists: 'Bazzi',
          genre: 'Pop',
          danceability: 0.71,
          energy: 0.789,
          key: 4,
          loudness: -3.874,
          mode: 1,
          speechiness: 0.0722,
          acousticness: 0.0161,
          instrumentalness: 0.00000277,
          liveness: 0.451,
          valence: 0.717,
          tempo: 142.929,
          duration_ms: 131064,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '2iUXsYOEPhVqEBwsqP70r',
          name: 'Youngblood',
          artists: '5 Seconds of Summer',
          genre: 'Pop',
          danceability: 0.596,
          energy: 0.854,
          key: 7,
          loudness: -5.114,
          mode: 0,
          speechiness: 0.463,
          acousticness: 0.0169,
          instrumentalness: 0,
          liveness: 0.124,
          valence: 0.152,
          tempo: 120.274,
          duration_ms: 203418,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '2xJCMIJfcNYDc5iR0sAm2',
          name: 'New Rules',
          artists: 'Dua Lipa',
          genre: 'Pop',
          danceability: 0.762,
          energy: 0.7,
          key: 9,
          loudness: -6.021,
          mode: 0,
          speechiness: 0.0694,
          acousticness: 0.00261,
          instrumentalness: 0.0000156,
          liveness: 0.153,
          valence: 0.608,
          tempo: 116.073,
          duration_ms: 209320,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '7qiZfU4dY1lWllzX7mPBI',
          name: 'Shape of You',
          artists: 'Ed Sheeran',
          genre: 'Pop',
          danceability: 0.825,
          energy: 0.652,
          key: 1,
          loudness: -3.183,
          mode: 0,
          speechiness: 0.0802,
          acousticness: 0.581,
          instrumentalness: 0,
          liveness: 0.0931,
          valence: 0.931,
          tempo: 95.977,
          duration_ms: 233713,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '45Egmo7icyopuzJN0oMEd',
          name: 'Love Lies (with Normani)',
          artists: 'Khalid',
          genre: 'R&B',
          danceability: 0.708,
          energy: 0.648,
          key: 6,
          loudness: -5.626,
          mode: 1,
          speechiness: 0.0449,
          acousticness: 0.0956,
          instrumentalness: 0,
          liveness: 0.134,
          valence: 0.338,
          tempo: 143.955,
          duration_ms: 201707,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '4e4fqjx0Izh4svvTef1z7',
          name: 'Meant to Be (feat. Florida Georgia Line)',
          artists: 'Bebe Rexha',
          genre: 'Pop',
          danceability: 0.642,
          energy: 0.772,
          key: 10,
          loudness: -6.61,
          mode: 1,
          speechiness: 0.0848,
          acousticness: 0.0476,
          instrumentalness: 0,
          liveness: 0.0646,
          valence: 0.589,
          tempo: 153.995,
          duration_ms: 164205,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '7m9OqQk4RVRkw9JJdeAw9',
          name: 'Jocelyn Flores',
          artists: 'XXXTENTACION',
          genre: 'Hip-Hop/Rap',
          danceability: 0.872,
          energy: 0.391,
          key: 0,
          loudness: -9.144,
          mode: 0,
          speechiness: 0.242,
          acousticness: 0.469,
          instrumentalness: 0.00000413,
          liveness: 0.297,
          valence: 0.437,
          tempo: 134.021,
          duration_ms: 119133,
          time_signature: 4,
          votes: 0,
        },
        {
          id: '0tgVpDi06FyKpA1z0VMD4',
          name: 'Perfect',
          artists: 'Ed Sheeran',
          genre: 'Pop',
          danceability: 0.599,
          energy: 0.448,
          key: 8,
          loudness: -6.312,
          mode: 1,
          speechiness: 0.0232,
          acousticness: 0.163,
          instrumentalness: 0,
          liveness: 0.106,
          valence: 0.168,
          tempo: 95.05,
          duration_ms: 263400,
          time_signature: 3,
          votes: 0,
        },
      ],
    };
  },
  methods: {
    selectMusic(event) {
      if (event) {
        const alreadyContainsMusic = this.selectedMusic.find(music => music.id === event.id);
        if (!alreadyContainsMusic) this.selectedMusic.push({ ...event });
      }
    },
    deleteMusic(index) {
      console.log(index);
      this.selectedMusic.splice(index, 1);
      this.search = '';
    },
  },
  computed: {
    filteredMusic() {
      return this.musics.filter(music => music.name
        .toString()
        .toLowerCase()
        .indexOf(this.search.toLowerCase()) >= 0);
    },
    isMusicComplete() {
      return this.selectedMusic.length >= 5;
    },
    isFormComplete() {
      return this.isMusicComplete && this.nickname;
    },
  },
};
</script>

<style lang="scss" scoped>
.vote-page-container {
  max-width: 400px;
  margin: 40px auto;
}
</style>
